### ISSUE TITLE
Bug - NavigationBar

### ISSUE THREAD

**Issue by malikdoksoz** [aqwert/flutter_platform_widgets#92] opened 2019-09-30 14:25 UTC
`[✓] Flutter (Channel dev, v1.10.6, on Mac OS X 10.14.6 18G103, locale tr-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

• No issues found!`

<img width="891" alt="Ekran Resmi 2019-09-30 17 21 16" src="https://user-images.githubusercontent.com/26676061/65887796-33d2b000-e3a7-11e9-926e-b66af2173bea.png">

**Comment by aqwert** [comment] 2019-10-01 02:32
This has been raised before. The issue is that the flutter team has changed the framework which is now on the dev branch. This package does not support the dev package and only supports the Stable branch. If you need to this to work I suggest to fork this project and make the change locally on your repo

**Comment by genert** [comment] 2019-10-14 12:15
@aqwert One question though, will you maintain backwards compatibility when such breaking changes happen from Flutter?

**Comment by aqwert** [comment] 2019-10-14 23:32
It is unlikely that can be done. Each release of the package will state what version of flutter it is targeting. The reason it needs to be with the latest flutter release is that for the most part they add extra properties to the widgets which I need to provide support for. This particular breaking change is rare but does highlight the difficulties of an ever evolving codebase.

**Comment by aqwert** [comment] 2019-10-14 23:34
I am closing this issue as there is a beta release 0.20.3-beta to fix this issue.1 available in pub.dev or one can reference yet beta branch in your pubspec file

**Closed by aqwert** 2019-10-14 23:34 UTC
