### ISSUE TITLE
platform_icons uses extension on BuildContext, causing conflict error

### ISSUE THREAD

**Issue by Bronixes** [aqwert/flutter_platform_widgets#170] opened 2020-05-12 12:58 UTC
change line 18 in flutter_plaftorm_widgets.dart from
`export 'src/platform_icons.dart'; `
to 
`export 'src/platform_icons.dart' hide BuildContext;`

**Comment by aqwert** [comment] 2020-05-16 09:28
Thanks. I usually only include the classes needed and for platform_icons this is not done. Will fix.

**Comment by Bronixes** [comment] 2020-05-20 13:11
For some reason if I used BuildContext reference anywhere in the app it showed conflict with platform_icons.dart, which has an extension on BuildContext.

As for now it seem to be fixed and doesn't affect me after updating to 0.50 version but idk why
![image](https://user-images.githubusercontent.com/45855362/82449769-66efbe00-9ab4-11ea-98e7-1bf024d449fa.png)

**Comment by aqwert** [comment] 2020-05-20 22:41
I have never seen this before and I did not do anything in this area for 0.50. If the issue is resolved for you could you close the issue. Thanks

**Closed** 2020-05-21 06:22 UTC
Labels: question
