### ISSUE TITLE
The plugin does not work with latest flutter beta

### ISSUE THREAD

**Issue by Sh1d0w** [aqwert/flutter_platform_widgets#6] opened 2018-09-21 04:23 UTC
Multiple errors are thrown if you use the plugin with the latest flutter beta.

**Comment by aqwert** [comment] 2018-09-21 07:06
Can you post what error you are getting. I got the latest and it does compile for me. Is this iOS or Android. If iOS did you upgrade to the latest xcode?

**Comment by Sh1d0w** [comment] 2018-09-21 07:11
Hi, yes it is iOS. The latest beta has some changes to the CupertinoNavigation widget which trows errors because tag property is not passed. Also I get some errors with PlatformScaffold.

**Comment by Sh1d0w** [comment] 2018-09-21 07:15
See this for example:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/nav_bar.dart#L192

Probably there are errors with other iOS widgets, as they were all updated in the latest beta, but I did not had a chance to test them all.

**Comment by Sh1d0w** [comment] 2018-09-21 07:30
I/flutter (17873): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (17873): The following assertion was thrown during a scheduler callback:
I/flutter (17873): There are multiple heroes that share the same tag within a subtree.
I/flutter (17873): Within each subtree for which heroes are to be animated (typically a PageRoute subtree), each Hero
I/flutter (17873): must have a unique non-null tag.
In this case, multiple heroes had the following tag: Default Hero tag for Cupertino navigation bars

**Comment by aqwert** [comment] 2018-09-21 07:49
Do you have a working sample that I could look at? Could be an issue with flutter itself and/or the way the cupertino widgets are being used

**Comment by Sh1d0w** [comment] 2018-09-21 07:59
@aqwert Unfortunately it is a private project I am working on and it is not possible. I will try to to setup a sample repo to reproduce and will let you know. Thanks for your quick responses.

**Comment by aqwert** [comment] 2018-10-14 08:12
I am closing this issue since it has been a while and I am unable to reproduce it

**Closed by aqwert** 2018-10-14 08:12 UTC
